version: '3'

services:
  database: 
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=apiTesteEteg
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  api:
    build: ./api
    container_name: api_container
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
    depends_on:
      - database
  app:
    build: ./frontend
    container_name: app_container
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true